---
minVersion:
  ios: 1.0.0
  android: 1.0.0
maintenance:
  on: false
  messages:
  - lang: en
    body: Maintenance break for 1.9.0 Update
  - lang: ko
    body: 1.9.0 버전업을 준비중입니다.
downloadUrl:
  ios: https://k2.biscuitlabs.io/ios
  android: https://k2.biscuitlabs.io/android
url:
  homepage: https://k2.biscuitgames.io
experimental: []
beta: []
tester:
- raindaysmain
connections:
  apiServer: https://k2-api.biscuitlabs.io/
  newsServer: https://k2-news.biscuitlabs.io/
