---
minVersion:
  ios: 1.0.0
  android: 1.0.0
maintenance:
  on: false
  message:
  - lang: en
    body: Maintenance break for 1.9.0 Update
  - lang: ko
    body: 1.9.0 버전업을 준비중입니다.
downloadUrl:
  ios: ''
  android: https://play.google.com/store/apps/details?id=games.biscuit.ethk
url:
  telegram: https://t.me/joinchat/IAL3EwvtSVMml_qkYPXbrw
experimental: []
beta: []
tester:
- raindaysmain
connections:
  apiServer: https://ethk-api.biscuit.games/
  lobbyServer: https://ethk-lobby.biscuit.games/
