---
minVersion:
  ios: 1.0.0
  android: 1.0.0
maintenance:
  on: false
  messages:
  - lang: en
    body: Maintenance break for 1.9.0 Update
  - lang: ko
    body: "![](http://eosknights.io/img/notice/banner.png =680x380)\n1.9.0 버전업을 준비중입니다."
downloadUrl:
  ios: https://k2.biscuitlabs.io/ios
  android: https://k2.biscuitlabs.io/android
url:
  homepage: https://k2.biscuitgames.io
experimental: []
tester:
- raindaysmain
connections:
  apiServer: http://121.168.149.101:8080
  shopServer: http://121.168.149.101:8081
  chatServer: ws://121.168.149.101:8765
  frontServer: http://121.168.149.101:8585
  blockExplorer: https://rinkeby.etherscan.io
  contractAddress: 0xF1a82eBaDcff995C177Ef9a88A0674c4a0A9B3A8
  marketURL: https://rinkeby.opensea.io
IAP: false
